### PR TITLE
Issue/setup felice domain and rest

### PR DESCRIPTION
**Pull request by azumari**
Within Logic.Felice.Domain:
- Created LogicHelper (empty)
- Created LogicMapper (empty)
- Created folder 'DomainModels'
- Created and populated AssociateDto under 'DomainModels'

### CODE REVIEW

**Comment by azumari** [comment]
Ready for review

**Comment by erchiggins** [comment]
@fredbelotte ready to merge!

**Comment by azumari** [comment]
localhost/workforce-felice-rest/ initialized

**Comment by azumari** [comment]
@erchiggins : This will need one last review to make sure everything is in order

**Comment by azumari** [comment]
@erchiggins @fredbelotte 
The changes to the Rest service have been made as requested.
If everything is in order, this should be ready to be merged with master so that we can get our services Live

**Comment by azumari** [comment]
@erchiggins @fredbelotte 
Changed TraineeID to AssociateID within AssociateDto
Added comment to 'Get' method within AssociateController

Ready for review

**Pull request merged**
